export enum EnvironmentEnum {
  PORT = 'PORT',
  TYPEORM_CONNECTION = 'TYPEORM_CONNECTION',
  TYPEORM_HOST = 'TYPEORM_HOST',
  TYPEORM_PORT = 'TYPEORM_PORT',
  TYPEORM_USERNAME = 'TYPEORM_USERNAME',
  TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
  TYPEORM_DATABASE = 'TYPEORM_DATABASE',
  TYPEORM_SYNCHRONIZE = 'TYPEORM_SYNCHRONIZE',
  NODE_ENV = 'NODE_ENV',
  TOKEN_SECRET = 'TOKEN_SECRET',
  COOKIE_LIFESPAN_IN_MILLISECONDS = 'COOKIE_LIFESPAN_IN_MILLISECONDS',
}

export enum EnvironmentType {
  production = 'production',
  development = 'development',
  staging = 'staging',
}
