export enum EnvironmentEnum {
  PORT = 'PORT',
  TYPEORM_CONNECTION = 'TYPEORM_CONNECTION',
  TYPEORM_HOST = 'TYPEORM_HOST',
  TYPEORM_PORT = 'TYPEORM_PORT',
  TYPEORM_USERNAME = 'TYPEORM_USERNAME',
  TYPEORM_PASSWORD = 'TYPEORM_PASSWORD',
  TYPEORM_DATABASE = 'TYPEORM_DATABASE',
  TYPEORM_SYNCHRONIZE = 'TYPEORM_SYNCHRONIZE',
}
